<a href="https://colab.research.google.com/github/mmedhat2/Projects/blob/main/Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Gathering Data**

In [3]:
import pandas as pd 
import numpy as np
import tweepy
import requests
import json
import csv



archivedf = pd.read_csv('twitter-archive-enhanced.csv')

In [4]:
archivedf.sample(4)

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
550,804738756058218496,NaN,NaN,2016-12-02 17:27:25 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Django. He accidentally opened the fro...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/804738756...,12,10,Django,None,None,None,None
1044,743609206067040256,NaN,NaN,2016-06-17 01:00:24 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Meet Stark. He just had his first ice cream co...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/743609206...,10,10,Stark,None,None,None,None
1493,692752401762250755,NaN,NaN,2016-01-28 16:53:37 +0000,"<a href=""http://twitter.com/download/iphone"" r...","""Hello yes could I get one pupper to go please...",NaN,NaN,NaN,https://twitter.com/dog_rates/status/692752401...,13,10,None,None,None,pupper,None
1286,708400866336894977,NaN,NaN,2016-03-11 21:15:02 +0000,"<a href=""http://vine.co"" rel=""nofollow"">Vine -...",RT if you are as ready for summer as this pup ...,NaN,NaN,NaN,https://vine.co/v/iHFqnjKVbIQ,12,10,None,None,None,None,None

In [5]:
imgdf = pd.DataFrame(columns=['tweet_id', 'jpg_url', 'img_num', 'p1', 'p1_conf',
                              'p1_dog', 'p2', 'p2_conf', 'p2_dog', 'p3', 'p3_conf', 'p3_dog'])
url = "https://d17h27t6h515a5.cloudfront.net/topher/2017/August/599fd2ad_image-predictions/image-predictions.tsv"

# Download the TSV file
response = requests.get(url)
response.raise_for_status()  # Raise an exception if the download fails

# Save the file to disk
with open("image-predictions.tsv", "r", encoding="utf-8") as file:
    # Create a CSV reader object
    reader = csv.reader(file, delimiter="\t")

    # Iterate over the rows and print the data
    for row in reader:
      imgdf.loc[len(imgdf)] = row
        

imgdf = imgdf.tail(-1)

FileNotFoundError: ignored

In [ ]:
consumer_key = 'mMOXGZbYfACvqLs7gtP04eJpL'
consumer_secret = 's4wn3A7bUC4OaqBfVYu7kWIx5gaR1Rjhht8WE158TTOOMxy9oN'
access_token = '1660264048825364480-cxfvCWnv7rsaV6FNht2yCydRrZk2nY'
access_secret = 'pmBTpXOGq7sJSlPHMp5JhvqTPr60UjUEOTTvTtD9I30NW'

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_secret)

api = tweepy.API(auth)